{
    "COMMENT": "NOTE: this file is autogenerated; built at Sat Oct 24 2020 16:47:35 GMT+0200 (GMT+02:00) with binhack-maker v1.1a",
    "binhacks": {
        "Priw8_th14pointdevice_binhack_252DA": {
            "addr": "Rx252DA",
            "code": "0f 87 [codecave:Priw8_th14pointdevice_customInsHandler]"
        },
        "Priw8_th14pointdevice_binhack_4DD91": {
            "addr": "Rx4DD91",
            "code": "e9 [codecave:Priw8_th14pointdevice_playerDeadHook]"
        }
    },
    "codecaves": {
        "Priw8_th14pointdevice_itemMgrCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_bulletMgrCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_bgCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_playerPosCopy": "00 00 00 00 00 00 00 00",
        "Priw8_th14pointdevice_enemyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_enemyCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_gameStateStructCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_memcpy4": "c1 e9 02 F3 A5 c3",
        "Priw8_th14pointdevice_allocIfNull": "8b 4c 24 04 8b 01 85 c0 0f 85 14 00 00 00 ff 74 24 08 b8 af 54 48 00 ff d0 83 c4 04 8b 4c 24 04 89 01 c2 08 00",
        "Priw8_th14pointdevice_customInsHandler": "3d a4 06 00 00 0f 84 07 00 00 00 b8 28 9c 42 00 ff e0 60 e8 08 00 00 00 61 b8 28 9c 42 00 ff e0 89 fe bf <codecave:Priw8_th14pointdevice_enemyPtr> 89 37 bf <codecave:Priw8_th14pointdevice_enemyCopyPtr> 68 0c 53 00 00 57 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 8b b6 ec 40 00 00 83 c6 04 b9 10 13 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 81 c7 54 01 00 00 81 c6 54 01 00 00 b9 70 00 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 83 c7 10 83 c6 10 b9 24 3e 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] bf <codecave:Priw8_th14pointdevice_enemyCopyPtr> 8b 3f 83 47 08 10 bf <codecave:Priw8_th14pointdevice_playerPosCopy> 8b 35 7c b6 4d 00 8d 86 ec 05 00 00 8b 18 89 1f 8b 58 04 89 5f 04 b8 <codecave:Priw8_th14pointdevice_itemMgrCopyPtr> 68 88 d8 dd 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 8b 35 60 b6 4d 00 89 c7 b9 88 d8 dd 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] b8 <codecave:Priw8_th14pointdevice_bulletMgrCopyPtr> 68 d0 f6 9b 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 8b 35 30 b5 4d 00 89 c7 b9 d0 f6 9b 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] b8 <codecave:Priw8_th14pointdevice_gameStateStructCopyPtr> 68 b0 02 00 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 be 28 58 4f 00 b9 b0 02 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] b8 <codecave:Priw8_th14pointdevice_bgCopyPtr> 68 a0 43 00 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 8b 35 28 b5 4d 00 b9 a0 43 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] c3",
        "Priw8_th14pointdevice_playerDeadHook": "60 e8 08 00 00 00 61 b8 d1 df 44 00 ff e0 89 fe a1 44 b5 4d 00 8b 80 d0 00 00 00 85 c0 0f 84 24 00 00 00 8b 18 f7 83 44 52 00 00 00 20 00 00 0f 85 0a 00 00 00 81 8b 44 52 00 00 00 00 00 02 8b 40 04 e9 d4 ff ff ff 6a 00 6a 01 b8 00 ac 43 00 ff d0 b8 50 d4 41 00 ff d0 c7 86 84 06 00 00 01 00 00 00 bf <codecave:Priw8_th14pointdevice_playerPosCopy> 8d 86 ec 05 00 00 8b 1f 89 18 8b 5f 04 89 58 04 8d 8e c0 82 01 00 6a 3c b8 00 8b 40 00 ff d0 b8 <codecave:Priw8_th14pointdevice_enemyPtr> 8b 00 8b 80 ec 40 00 00 83 c0 08 8b 88 14 10 00 00 b8 b0 45 48 00 ff d0 be <codecave:Priw8_th14pointdevice_enemyCopyPtr> 8b 36 b8 <codecave:Priw8_th14pointdevice_enemyPtr> 8b 00 8b b8 ec 40 00 00 83 c7 04 b9 10 13 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 81 c7 54 01 00 00 81 c6 54 01 00 00 b9 70 00 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 83 c6 10 83 c7 10 b9 24 3e 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] be <codecave:Priw8_th14pointdevice_itemMgrCopyPtr> 8b 36 8b 3d 60 b6 4d 00 b9 88 d8 dd 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] be <codecave:Priw8_th14pointdevice_bulletMgrCopyPtr> 8b 36 8b 3d 30 b5 4d 00 b9 d0 f6 9b 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] bf 28 58 4f 00 be <codecave:Priw8_th14pointdevice_gameStateStructCopyPtr> 8b 36 b9 b0 02 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] be <codecave:Priw8_th14pointdevice_bgCopyPtr> 8b 36 8b 3d 28 b5 4d 00 b9 a0 43 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 8b 0d 7c b6 4d 00 b8 70 f9 44 00 ff d0 8b 0d 50 b5 4d 00 a1 74 58 4f 00 50 a1 70 58 4f 00 50 b8 d0 4f 43 00 ff d0 b8 b0 fc 47 00 ff d0 89 c6 8b 0d 3c b5 4d 00 8b 49 10 68 c4 00 00 00 56 b8 70 fd 47 00 ff d0 31 c0 89 46 3c 89 46 40 89 46 44 89 86 9c 05 00 00 89 86 a0 05 00 00 89 86 a4 05 00 00 56 54 b8 90 e8 47 00 ff d0 c3",
        "protection": "0x40"
    }
}