{
    "COMMENT": "NOTE: this file is autogenerated; built at Sat Nov 14 2020 16:55:04 GMT+0100 (GMT+01:00) with binhack-maker v1.1a",
    "binhacks": {
        "Priw8_th14pointdevice_binhack_252DA": {
            "addr": "Rx252DA",
            "code": "0f 87 [codecave:Priw8_th14pointdevice_customInsHandler]"
        },
        "Priw8_th14pointdevice_binhack_4DD91": {
            "addr": "Rx4DD91",
            "code": "e9 [codecave:Priw8_th14pointdevice_playerDeadHook]"
        },
        "Priw8_th14pointdevice_binhack_39844": {
            "addr": "Rx39844",
            "code": "bb 01 00 00 00 90 90"
        },
        "Priw8_th14pointdevice_binhack_397BB": {
            "addr": "Rx397BB",
            "code": "e9 [codecave:Priw8_th14pointdevice_replaceLifePiece]"
        },
        "Priw8_th14pointdevice_binhack_82552": {
            "addr": "Rx82552",
            "code": "e9 [codecave:Priw8_th14pointdevice_logSubCall_ins11] 90 90"
        },
        "Priw8_th14pointdevice_binhack_8244C": {
            "addr": "Rx8244C",
            "code": "e9 [codecave:Priw8_th14pointdevice_logSubCall_ins15] 90"
        },
        "Priw8_th14pointdevice_binhack_82470": {
            "addr": "Rx82470",
            "code": "e9 [codecave:Priw8_th14pointdevice_logSubCall_ins16] 90"
        }
    },
    "codecaves": {
        "Priw8_th14pointdevice_itemMgrCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_bulletMgrCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_bgCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_playerPosCopy": "00 00 00 00 00 00 00 00",
        "Priw8_th14pointdevice_enemyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_enemyCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_gameStateStructCopyPtr": "00 00 00 00",
        "Priw8_th14pointdevice_memcpy4": "c1 e9 02 F3 A5 c3",
        "Priw8_th14pointdevice_cpyGameState": "83 c7 08 83 c6 08 8b 06 89 07 83 c7 10 83 c6 10 8b 06 89 07 83 c7 0c 83 c6 0c 8b 06 89 07 83 c7 0c 83 c6 0c 8b 06 89 07 83 c7 0c 83 c6 0c 8b 06 89 07 83 c7 04 83 c6 04 8b 06 89 07 83 c7 08 83 c6 08 8b 06 89 07 83 c7 04 83 c6 04 8b 06 89 07 83 c7 24 83 c6 24 8b 06 89 07 c3",
        "Priw8_th14pointdevice_allocIfNull": "8b 4c 24 04 8b 01 85 c0 0f 85 14 00 00 00 ff 74 24 08 b8 af 54 48 00 ff d0 83 c4 04 8b 4c 24 04 89 01 c2 08 00",
        "Priw8_th14pointdevice_customInsHandler": "3d a4 06 00 00 0f 84 07 00 00 00 b8 28 9c 42 00 ff e0 60 e8 08 00 00 00 61 b8 28 9c 42 00 ff e0 89 fe bf <codecave:Priw8_th14pointdevice_enemyPtr> 89 37 bf <codecave:Priw8_th14pointdevice_enemyCopyPtr> 68 0c 53 00 00 57 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 8b b6 ec 40 00 00 83 c6 04 b9 10 13 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 81 c7 54 01 00 00 81 c6 54 01 00 00 b9 70 00 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 83 c7 10 83 c6 10 b9 24 3e 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] bf <codecave:Priw8_th14pointdevice_enemyCopyPtr> 8b 3f 83 47 08 10 bf <codecave:Priw8_th14pointdevice_playerPosCopy> 8b 35 7c b6 4d 00 8d 86 ec 05 00 00 8b 18 89 1f 8b 58 04 89 5f 04 b8 <codecave:Priw8_th14pointdevice_itemMgrCopyPtr> 68 88 d8 dd 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 8b 35 60 b6 4d 00 89 c7 b9 88 d8 dd 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] b8 <codecave:Priw8_th14pointdevice_bulletMgrCopyPtr> 68 d0 f6 9b 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 8b 35 30 b5 4d 00 89 c7 b9 d0 f6 9b 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] b8 <codecave:Priw8_th14pointdevice_gameStateStructCopyPtr> 68 b0 02 00 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 be 28 58 4f 00 e8 [codecave:Priw8_th14pointdevice_cpyGameState] b8 <codecave:Priw8_th14pointdevice_bgCopyPtr> 68 a0 43 00 00 50 e8 [codecave:Priw8_th14pointdevice_allocIfNull] 89 c7 8b 35 28 b5 4d 00 b9 a0 43 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] c3",
        "Priw8_th14pointdevice_playerDeadHook": "60 e8 08 00 00 00 61 b8 d1 df 44 00 ff e0 89 fe a1 44 b5 4d 00 8b 80 d0 00 00 00 85 c0 0f 84 24 00 00 00 8b 18 f7 83 44 52 00 00 00 20 00 00 0f 85 0a 00 00 00 81 8b 44 52 00 00 00 00 00 02 8b 40 04 e9 d4 ff ff ff 6a 00 6a 01 b8 00 ac 43 00 ff d0 b8 50 d4 41 00 ff d0 c7 86 84 06 00 00 01 00 00 00 bf <codecave:Priw8_th14pointdevice_playerPosCopy> 8d 86 ec 05 00 00 8b 1f 89 18 8b 5f 04 89 58 04 8d 8e c0 82 01 00 6a 3c b8 00 8b 40 00 ff d0 b8 <codecave:Priw8_th14pointdevice_enemyPtr> 8b 00 8b 80 ec 40 00 00 83 c0 08 8b 88 14 10 00 00 b8 b0 45 48 00 ff d0 be <codecave:Priw8_th14pointdevice_enemyCopyPtr> 8b 36 b8 <codecave:Priw8_th14pointdevice_enemyPtr> 8b 00 8b b8 ec 40 00 00 83 c7 04 b9 10 13 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 81 c7 54 01 00 00 81 c6 54 01 00 00 b9 70 00 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 83 c6 10 83 c7 10 b9 24 3e 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] be <codecave:Priw8_th14pointdevice_itemMgrCopyPtr> 8b 36 8b 3d 60 b6 4d 00 b9 88 d8 dd 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] be <codecave:Priw8_th14pointdevice_bulletMgrCopyPtr> 8b 36 8b 3d 30 b5 4d 00 b9 d0 f6 9b 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] bf 28 58 4f 00 be <codecave:Priw8_th14pointdevice_gameStateStructCopyPtr> 8b 36 e8 [codecave:Priw8_th14pointdevice_cpyGameState] be <codecave:Priw8_th14pointdevice_bgCopyPtr> 8b 36 8b 3d 28 b5 4d 00 b9 a0 43 00 00 e8 [codecave:Priw8_th14pointdevice_memcpy4] 8b 0d 7c b6 4d 00 b8 70 f9 44 00 ff d0 8b 0d 50 b5 4d 00 a1 74 58 4f 00 50 a1 70 58 4f 00 50 b8 d0 4f 43 00 ff d0 b8 b0 fc 47 00 ff d0 89 c6 8b 0d 3c b5 4d 00 8b 49 10 68 c4 00 00 00 56 b8 70 fd 47 00 ff d0 31 c0 89 46 3c 89 46 40 89 46 44 89 86 9c 05 00 00 89 86 a0 05 00 00 89 86 a4 05 00 00 56 54 b8 90 e8 47 00 ff d0 c3",
        "Priw8_th14pointdevice_replaceLifePiece": "8b 5d 08 56 57 83 fb 04 0f 85 ac 00 00 00 bb <codecave:Priw8_th14pointdevice_FLOAT_32> 83 ec 08 89 e7 8b 75 0c f3 0f 10 06 f3 0f 58 03 f3 0f 11 07 f3 0f 10 46 04 f3 0f 11 47 04 6a 00 83 ec 0c c7 44 24 08 cd cc 0c 40 c7 44 24 04 db 0f c9 bf 57 6a 06 b8 b0 97 43 00 ff d0 f3 0f 10 06 f3 0f 5c 03 f3 0f 11 07 6a 00 83 ec 0c c7 44 24 08 cd cc 0c 40 c7 44 24 04 db 0f c9 bf 57 6a 06 b8 b0 97 43 00 ff d0 f3 0f 10 06 f3 0f 11 07 f3 0f 10 46 04 f3 0f 5c 03 f3 0f 11 47 04 6a 00 83 ec 0c c7 44 24 08 cd cc 0c 40 c7 44 24 04 db 0f c9 bf 57 6a 06 b8 b0 97 43 00 ff d0 83 c4 08 b8 5a 99 43 00 ff e0 b8 c0 97 43 00 ff e0",
        "Priw8_th14pointdevice_FLOAT_32": "00 00 00 42",
        "Priw8_th14pointdevice_logSubCall_ins11": "60 e8 [codecave:Priw8_th14pointdevice_logSubCall] 61 51 6a 00 c6 41 0c 00 b9 59 25 48 00 ff e1",
        "Priw8_th14pointdevice_logSubCall_ins15": "60 e8 [codecave:Priw8_th14pointdevice_logSubCall] 61 8b 8f 14 10 00 00 b8 52 24 48 00 ff e0",
        "Priw8_th14pointdevice_logSubCall_ins16": "60 e8 [codecave:Priw8_th14pointdevice_logSubCall] 61 8b 41 10 83 c0 04 c1 e8 02 f6 41 08 02 8b 44 81 10 b9 81 24 48 00 ff e1",
        "Priw8_th14pointdevice_logSubCall": "8d 41 14 50 0f b7 41 04 83 f8 0b 0f 85 0a 00 00 00 b8 <codecave:Priw8_th14pointdevice_SUBCALL_CALL> e9 18 00 00 00 83 f8 0f 0f 85 0a 00 00 00 b8 <codecave:Priw8_th14pointdevice_SUBCALL_CALLASYNC> e9 05 00 00 00 b8 <codecave:Priw8_th14pointdevice_SUBCALL_CALLASYNCID> 50 8b 87 14 10 00 00 8b 80 e4 11 00 00 50 b8 <codecave:Priw8_th14pointdevice_SUBCALL_FORMAT> 50 b8 <codecave:Priw8_th14pointdevice_SUBCALL_MYCOOLBUFFER> 50 b8 df 5d 48 00 ff d0 83 c4 14 b8 <codecave:Priw8_th14pointdevice_SUBCALL_LOG_FILE_HANDLE> 8b 00 85 c0 0f 85 28 00 00 00 51 a1 80 10 4b 00 6a 00 68 80 00 00 00 6a 02 6a 00 6a 01 68 00 00 00 40 b9 <codecave:Priw8_th14pointdevice_SUBCALL_FILENAME> 51 ff d0 b9 <codecave:Priw8_th14pointdevice_SUBCALL_LOG_FILE_HANDLE> 89 01 59 89 c6 6a 00 54 b9 <codecave:Priw8_th14pointdevice_SUBCALL_MYCOOLBUFFER> e8 10 00 00 00 50 b9 <codecave:Priw8_th14pointdevice_SUBCALL_MYCOOLBUFFER> 51 56 a1 9c 10 4b 00 ff d0 c3 31 c0 0f b6 11 85 d2 0f 84 07 00 00 00 40 41 e9 ee ff ff ff c3",
        "Priw8_th14pointdevice_SUBCALL_LOG_FILE_HANDLE": "00 00 00 00",
        "Priw8_th14pointdevice_SUBCALL_MYCOOLBUFFER": "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
        "Priw8_th14pointdevice_SUBCALL_FILENAME": "74 68 31 34 73 75 62 63 61 6c 6c 73 2e 6c 6f 67 00",
        "Priw8_th14pointdevice_SUBCALL_FORMAT": "28 25 64 29 20 25 73 3a 20 25 73 0A 00",
        "Priw8_th14pointdevice_SUBCALL_CALL": "63 61 6c 6c 00",
        "Priw8_th14pointdevice_SUBCALL_CALLASYNC": "63 61 6c 6c 41 73 79 6e 63 00",
        "Priw8_th14pointdevice_SUBCALL_CALLASYNCID": "63 61 6c 6c 41 73 79 6e 63 49 64 00",
        "protection": "0x40"
    }
}